[project]
name = "assignment1-semana2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gzapata9", email = "guillermozapata99@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
assignment1-semana2 = "assignment1_semana2:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
